---
- name: Install Java8
  yum:
    name: java-1.8.0-openjdk.x86_64

- name: Enable Java8
  shell: |
    /usr/sbin/alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
    /usr/sbin/alternatives --set javac /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/javac
    exit 0
- name: Enable Jenkins Repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Enable rpm_key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Install Jenkins
  yum:
    name: "jenkins"
    state: latest

- name: Enable jenkins
  service:
    name: jenkins
    state: started
